name: diagagri22
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-277 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  sqflite: ^2.2.8+4
  sqflite_common: ^2.4.2+2
  sqflite_common_ffi_web: ^0.3.5+1
  path: ^1.8.3
  shared_preferences: ^2.0.18
  connectivity_plus: ^4.0.1
  http: ^0.13.5
  toast: ^0.3.0
  # google_mobile_ads: ^2.0.1
  webview_flutter: ^4.2.2
  avatar_view: ^1.0.1
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+1
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.10
  path_provider: ^2.0.11
  path_provider_platform_interface: ^2.0.4
  args: ^2.3.1
  image: ^4.0.15
  yaml: ^3.1.1
  cpf_util: ^3.0.1
  dio: ^5.2.0+1
  dropdown_search: ^5.0.6
  brasil_fields: ^1.12.0
  google_maps_flutter: ^2.1.10
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  googleapis: ^11.2.0
  flex_color_scheme: ^4.2.0
  google_fonts: ^4.0.4
  flex_seed_scheme: ^1.3.0




  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  mobx_codegen: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
flutter_native_splash:
   color: "#1c5709"
   image: "assets/images/plantio_splash.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/plantio_splash.png
    - assets/
    - assets/sql/
    - assets/images/  
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Pacifico
      fonts:
          - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Bebas
      fonts:
          - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Source Sans
      fonts:
          - asset: assets/fonts/SourceSansPro-Regular.ttf    
           
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
